language: node_js
os:
- linux
node_js: 8
script:
- yarn test:e2e
addons:
  browserstack:
    username: andrasserfozo1
    access_key:
      secure: "mzNKvaB2u3/0DSINPpr6xhYljBEWT+Od+wrWtgd7Xz6GBM1cL3mwfs/wsJhufJ3bc/D91LK5EnQeMMqAxWf+ihDygcxWb2P02gGcGJ/XnulN8sgFMml+xfC4N+lB3D6L9UQNEpNZzNv4ikI/4zvt1iv/lr9AFHwZsfVqOVSWcX30ltFIqwSp98C1ozLlUBzjE3QjB2dd/RflpthQhc0BJxPESqrU/mmz02hZoCeCD/ecNVnE+fo3irZ6kjTKLJQygNJzs6yrkGG+9Ab5glDNt8DRj5Pg17N3TP9hS4cbI5in1fvxVmv3eJwb6RFFxXUmNTA6BohPgOl/yWq17bgXIwWNI0Pf3FOxr5iHS5VtOcJLULhA1t6pZf2YyxGzfUUNc7I3U34zIhJzyoCf6xzCR24w8RUbkKgPUchcHVY7fnSBmZQeuYzS/cZNyaUyMYb9HmSWzmwqOISCnu6IrFAeFI2ypEinjllstillguowek1i7u8v5LqL7gAxmenfAXqFo5OITeBPP4W2HMBQQ8KiN8HaSDYqSq2wS996haS7hJXJXIsy5HN2Om0G8vU3Yfj4/4BZNx/DYYAgEdiduf49o1EYJAbj4bkFApKzqC9iif3cmVEiOwnT2oqf5b0Jq3f2M52WpJdAm0V9I3Y7YTnNEGGLAy46LzsMz9URLhZddMk="
env:
  matrix:
  - BROWSERSTACK_USERNAME=andrasserfozo1
  global:
  - secure: mzNKvaB2u3/0DSINPpr6xhYljBEWT+Od+wrWtgd7Xz6GBM1cL3mwfs/wsJhufJ3bc/D91LK5EnQeMMqAxWf+ihDygcxWb2P02gGcGJ/XnulN8sgFMml+xfC4N+lB3D6L9UQNEpNZzNv4ikI/4zvt1iv/lr9AFHwZsfVqOVSWcX30ltFIqwSp98C1ozLlUBzjE3QjB2dd/RflpthQhc0BJxPESqrU/mmz02hZoCeCD/ecNVnE+fo3irZ6kjTKLJQygNJzs6yrkGG+9Ab5glDNt8DRj5Pg17N3TP9hS4cbI5in1fvxVmv3eJwb6RFFxXUmNTA6BohPgOl/yWq17bgXIwWNI0Pf3FOxr5iHS5VtOcJLULhA1t6pZf2YyxGzfUUNc7I3U34zIhJzyoCf6xzCR24w8RUbkKgPUchcHVY7fnSBmZQeuYzS/cZNyaUyMYb9HmSWzmwqOISCnu6IrFAeFI2ypEinjllstillguowek1i7u8v5LqL7gAxmenfAXqFo5OITeBPP4W2HMBQQ8KiN8HaSDYqSq2wS996haS7hJXJXIsy5HN2Om0G8vU3Yfj4/4BZNx/DYYAgEdiduf49o1EYJAbj4bkFApKzqC9iif3cmVEiOwnT2oqf5b0Jq3f2M52WpJdAm0V9I3Y7YTnNEGGLAy46LzsMz9URLhZddMk=
